name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # Update every hour
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Only-Bugs
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          plugin_activity_days: 14
